// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjPj4YOTUKqCA-ki-pOO_Whd1qnsaLeXE',
    appId: '1:91884402726:web:ef41dda88e79d1e3d38ee7',
    messagingSenderId: '91884402726',
    projectId: 'aiclassificationapp',
    authDomain: 'aiclassificationapp.firebaseapp.com',
    storageBucket: 'aiclassificationapp.firebasestorage.app',
    measurementId: 'G-K4X3ZGS4LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1aiCR_grtA-94CQqh1jCbQwfvLhyLWw',
    appId: '1:91884402726:android:e696a9bd30dc7acbd38ee7',
    messagingSenderId: '91884402726',
    projectId: 'aiclassificationapp',
    storageBucket: 'aiclassificationapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD518KaXYWmzaVCu-AEPPMTk43whFxYZdM',
    appId: '1:91884402726:ios:1350ee5d77fab4ddd38ee7',
    messagingSenderId: '91884402726',
    projectId: 'aiclassificationapp',
    storageBucket: 'aiclassificationapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterUpgrdeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD518KaXYWmzaVCu-AEPPMTk43whFxYZdM',
    appId: '1:91884402726:ios:1350ee5d77fab4ddd38ee7',
    messagingSenderId: '91884402726',
    projectId: 'aiclassificationapp',
    storageBucket: 'aiclassificationapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterUpgrdeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjPj4YOTUKqCA-ki-pOO_Whd1qnsaLeXE',
    appId: '1:91884402726:web:f5fe16c7d8f1f007d38ee7',
    messagingSenderId: '91884402726',
    projectId: 'aiclassificationapp',
    authDomain: 'aiclassificationapp.firebaseapp.com',
    storageBucket: 'aiclassificationapp.firebasestorage.app',
    measurementId: 'G-6MNCZ6D8LN',
  );
}
